version: "3.8"

services:
  db:
    build: ./db
    container_name: tienda-ropa-db
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: tienda_ropa
      MYSQL_USER: alumno
      MYSQL_PASSWORD: alumno123
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tienda-net

  backend:
    build: ./backend
    container_name: tienda-ropa-backend
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: admin123
      DB_NAME: tienda_ropa
      DB_PORT: 3306
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - tienda-net

  frontend:
    build: ./frontend
    container_name: tienda-ropa-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - tienda-net

volumes:
  dbdata:

networks:
  tienda-net:
    driver: bridge
